
name: Build mpv static
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_git_repo:
        description: "aarch64"
        required: true
        default: "to change fedora images url"


env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download-releases
        id: download
        run: |
          curl -LO "https://github.com/fedora-remix-mobility/fedora-kiwi-descriptions/releases/download/2025-04-04/Fedora-SDM845-Remix.tar.xz"
          pwd
          ls -ltrh
          
          echo "::set-output name=status::success"
          

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: fedora-aarch64
          path: /home/pintcat/ubin/*

      - name: Upload image to Release
        uses: ncipollo/release-action@main
        if: steps.download.outputs.status == 'success' && !cancelled()
        with:
          tag: fedora_oneplus6t_${{ env.COMPILE_STARTINGTIME }}
          artifacts: /home/pintcat/ubin/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is fedora-oneplus6t-image ${{ env.LINUX_GITURL }}
